// This file contains the complete list of every railway station in Victoria served by Metro trains Melbourne
// it also contains each stations unique id number (1xxx) and are all listed in stopping order

// new line template;
//    0 : {stationName : '', stationId : },

// up to date as of 9th of March 2023

var alameinLine = {     // 14 stops
    0 : {stationName : 'Alamein', stationId : 1002},
    1 : {stationName : 'Ashburton', stationId : 1010},
    2 : {stationName : 'Burwood', stationId : 1031},
    3 : {stationName : 'Hartwell', stationId : 1087},
    4 : {stationName : 'Willison', stationId : 1213},
    5 : {stationName : 'Riversdale', stationId : 1166},
    6 : {stationName : 'Camberwell', stationId : 1032},
    7 : {stationName : 'Auburn', stationId : 1012},
    8 : {stationName : 'Glenferrie', stationId : 1080},
    9 : {stationName : 'Hawthorn', stationId : 1090},
    10 : {stationName : 'Burnley', stationId : 1030},
    11 : {stationName : 'East Richmond', stationId : 1059},
    12 : {stationName : 'Richmond', stationId : 1162},
    13 : {stationName : 'Flinders Street', stationId : 1071}
}

var belgraveLine = {    // 27 stops
    0 : {stationName : 'Belgrave', stationId : 1018},
    1 : {stationName : 'Tecoma', stationId : 1191},
    2 : {stationName : 'Upwey', stationId : 1200},
    3 : {stationName : 'Upper Ferntree Gully', stationId : 1199},
    4 : {stationName : 'Ferntree Gully', stationId : 1067},
    5 : {stationName : 'Boronia', stationId : 1025},
    6 : {stationName : 'Bayswater', stationId : 1016},
    7 : {stationName : 'Heathmont', stationId : 1092},
    8 : {stationName : 'Ringwood', stationId : 1163},
    9 : {stationName : 'Heatherdale', stationId : 1091},
    10 : {stationName : 'Mitcham', stationId : 1128},
    11 : {stationName : 'Nunawading', stationId : 1148},
    12 : {stationName : 'Blackburn', stationId : 1023},
    13 : {stationName : 'Laburnum', stationId : 1111},
    14 : {stationName : 'Box Hill', stationId : 1026},
    15 : {stationName : 'Mont Albert', stationId : 1129},       // Mont albert station and Surrey Hills station are being
    16 : {stationName : 'Surrey Hills', stationId : 1189},      // demolished and replaced by a single new station 'Union'
    17 : {stationName : 'Chatham', stationId : 1037},
    18 : {stationName : 'Canterbury', stationId : 1033},
    19 : {stationName : 'East Camberwell', stationId : 1057},
    20 : {stationName : 'Camberwell', stationId : 1032},
    21 : {stationName : 'Auburn', stationId : 1012},
    22 : {stationName : 'Glenferrie', stationId : 1080},
    23 : {stationName : 'Hawthorn', stationId : 1090},
    23 : {stationName : 'Burnley', stationId : 1030},
    24 : {stationName : 'East Richmond', stationId : 1059},
    25 : {stationName : 'Richmond', stationId : 1162},
    26 : {stationName : 'Flinders Street', stationId : 1071}
}

var craigieburnLine = { // 18 stops
    0 : {stationName : 'Craigieburn', stationId : 1044},
    1 : {stationName : 'Roxburgh Park', stationId : 1219},
    2 : {stationName : 'Coolaroo', stationId : 1221},
    3 : {stationName : 'Broadmeadows', stationId : 1028},
    4 : {stationName : 'Jacana', stationId : 1102},
    5 : {stationName : 'Glenroy', stationId : 1082},
    6 : {stationName : 'Oak Park', stationId : 1149},
    7 : {stationName : 'Pascoe Vale', stationId : 1156},
    8 : {stationName : 'Strathmore', stationId : 1186},
    9 : {stationName : 'Glenbervie', stationId : 1079},
    10 : {stationName : 'Essendon', stationId : 1064},
    11 : {stationName : 'Moonee Ponds', stationId : 1131},
    12 : {stationName : 'Ascot Vale', stationId : 1009},
    13 : {stationName : 'Newmarket', stationId : 1140},
    14 : {stationName : 'Kensington', stationId : 1108},
    15 : {stationName : 'North Melbourne', stationId : 1144},
    16 : {stationName : 'Southern Cross', stationId : 1181},
    17 : {stationName : 'Flinders Street', stationId : 1071},
}

var cranbourneLine = {  // 23 stops
    0 : {stationName : 'Cranbourne', stationId : 1045},
    1 : {stationName : 'Merinda Park', stationId : 1123},
    2 : {stationName : 'Lynbrook', stationId : 1222},
    3 : {stationName : 'Dandenong', stationId : 1049},
    4 : {stationName : 'Yarraman', stationId : 1215},
    5 : {stationName : 'Noble Park', stationId : 1142},
    6 : {stationName : 'Sandown Park', stationId : 1172},
    7 : {stationName : 'Springvale', stationId : 1183},
    8 : {stationName : 'Westall', stationId : 1208},
    9 : {stationName : 'Clayton', stationId : 1040},
    10 : {stationName : 'Huntingdale', stationId : 1099},
    11 : {stationName : 'Oakleigh', stationId : 1150},
    12 : {stationName : 'Hughesdale', stationId : 1098},
    13 : {stationName : 'Murrumbeena', stationId : 1138},
    14 : {stationName : 'Carnegie', stationId : 1034},
    15 : {stationName : 'Caulfield', stationId : 1036},
    16 : {stationName : 'Malvern', stationId : 1118},
    17 : {stationName : 'Armadale', stationId : 1008},
    18 : {stationName : 'Toorak', stationId : 1194},
    19 : {stationName : 'Hawksburn', stationId : 1089},
    20 : {stationName : 'South Yarra', stationId : 1180},
    21 : {stationName : 'Richmond', stationId : 1162},
    22 : {stationName : 'Flinders Street', stationId : 1071},
}

var frankstonLine = {   // 28 stops
    0 : {stationName : 'Frankston', stationId : 1073},
    1 : {stationName : 'Kananook', stationId : 1106},
    2 : {stationName : 'Seaford', stationId : 1174},
    3 : {stationName : 'Carrum', stationId : 1035},
    4 : {stationName : 'Bonbeach', stationId : 1024},
    5 : {stationName : 'Chelsea', stationId : 1038},
    6 : {stationName : 'Edithvale', stationId : 1060},
    7 : {stationName : 'Aspendale', stationId : 1011},
    8 : {stationName : 'Mordialloc', stationId : 1134},
    9 : {stationName : 'Parkdale', stationId : 1154},
    10 : {stationName : 'Mentone', stationId : 1122},
    11 : {stationName : 'Cheltenham', stationId : 1039},
    12 : {stationName : 'Southland', stationId : 1001},
    13 : {stationName : 'Highett', stationId : 1095},
    14 : {stationName : 'Moorabbin', stationId : 1132},
    15 : {stationName : 'Patterson', stationId : 1157},
    16 : {stationName : 'Bentleigh', stationId : 1020},
    17 : {stationName : 'McKinnon', stationId : 1119},
    18 : {stationName : 'Ormond', stationId : 1152},
    19 : {stationName : 'Glenhuntly', stationId : 1081},
    20 : {stationName : 'Caulfield', stationId : 1036},
    21 : {stationName : 'Malvern', stationId : 1118},
    22 : {stationName : 'Armadale', stationId : 1008},
    23 : {stationName : 'Toorak', stationId : 1194},
    24 : {stationName : 'Hawksburn', stationId : 1089},
    25 : {stationName : 'South Yarra', stationId : 1180},
    26 : {stationName : 'Richmond', stationId : 1162},
    27 : {stationName : 'Flinders Street', stationId : 1071},
}

var glenWaverlyLine = { // 16 stops
    0 : {stationName : 'Glen Waverly', stationId : 1078},
    1 : {stationName : 'Syndal', stationId : 1190},
    2 : {stationName : 'Mount Waverly', stationId : 1137},
    3 : {stationName : 'Jordanville', stationId : 1105},
    4 : {stationName : 'Homesglen', stationId : 1096},
    5 : {stationName : 'East Malvern', stationId : 1058},
    6 : {stationName : 'Darling', stationId : 1051},
    7 : {stationName : 'Glen Iris', stationId : 1077},
    8 : {stationName : 'Gardiner', stationId : 1075},
    9 : {stationName : 'Tooronga', stationId : 1195},
    10 : {stationName : 'Kooyong', stationId : 1110},
    11 : {stationName : 'Heyington', stationId : 1094},
    12 : {stationName : 'Burnley', stationId : 1030},
    13 : {stationName : 'East Richmond', stationId : 1059},
    14 : {stationName : 'Richmond', stationId : 1162},
    15 : {stationName : 'Flinders Street', stationId : 1071}
}

var hurstbridgeLine = { // 24 stops
    0 : {stationName : 'Hurtsbridge', stationId : 1100},
    1 : {stationName : 'Wattle Glen', stationId : 1204},
    2 : {stationName : 'Diamond Creek', stationId : 1054},
    3 : {stationName : 'Eltham', stationId : 1062},
    4 : {stationName : 'Montmorency', stationId : 1130},
    5 : {stationName : 'Greensborough', stationId : 1084},
    6 : {stationName : 'Watsonia', stationId : 1203},
    7 : {stationName : 'Macleod', stationId : 1117},
    8 : {stationName : 'Rosanna', stationId : 1168},
    9 : {stationName : 'Heidelberg', stationId : 1093},
    10 : {stationName : 'Eaglemont', stationId : 1056},
    11 : {stationName : 'Ivanhoe', stationId : 1101},
    12 : {stationName : 'Darebin', stationId : 1050},
    13 : {stationName : 'Alphington', stationId : 1004},
    14 : {stationName : 'Fairfield', stationId : 1065},
    15 : {stationName : 'Dennis', stationId : 1053},
    16 : {stationName : 'Westgarth', stationId : 1209},
    17 : {stationName : 'Clifton Hill', stationId : 1041},
    18 : {stationName : 'Victoria Park', stationId : 1201},
    19 : {stationName : 'Collingwood', stationId : 1043},
    20 : {stationName : 'North Richmond', stationId : 1145},
    21 : {stationName : 'West Richmond', stationId : 1207},
    22 : {stationName : 'Jolimont', stationId : 1104},
    23 : {stationName : 'Flinders Street', stationId : 1071},
}

var lilydaleLine = {    // 24 stops
    0 : {stationName : 'Lilydale', stationId : 1115},
    1 : {stationName : 'Mooroolbark', stationId : 1133},
    2 : {stationName : 'Croydon', stationId : 1048},
    3 : {stationName : 'Ringwood East', stationId : 1164},
    4 : {stationName : 'Ringwood', stationId : 1163},
    5 : {stationName : 'Heatherdale', stationId : 1091},
    6 : {stationName : 'Mitcham', stationId : 1128},
    7 : {stationName : 'Nunawading', stationId : 1148},
    8 : {stationName : 'Blackburn', stationId : 1023},
    9 : {stationName : 'Laburnum', stationId : 1111},
    10 : {stationName : 'Box Hill', stationId : 1026},
    11 : {stationName : 'Mont Albert', stationId : 1129},       // Mont albert station and Surrey Hills station are being
    12 : {stationName : 'Surrey Hills', stationId : 1189},      // demolished and replaced by a single new station 'Union'
    13 : {stationName : 'Chatham', stationId : 1037},
    14 : {stationName : 'Canterbury', stationId : 1033},
    15 : {stationName : 'East Camberwell', stationId : 1057},
    16 : {stationName : 'Camberwell', stationId : 1032},
    17 : {stationName : 'Auburn', stationId : 1012},
    18 : {stationName : 'Glenferrie', stationId : 1080},
    19 : {stationName : 'Hawthorn', stationId : 1090},
    20 : {stationName : 'Burnley', stationId : 1030},
    21 : {stationName : 'East Richmond', stationId : 1059},
    22 : {stationName : 'Richmond', stationId : 1162},
    23 : {stationName : 'Flinders Street', stationId : 1071}
}

var merndaLine = {      // 25 stops
    0 : {stationName : 'Mernda', stationId : 1228},
    1 : {stationName : 'Hawkstowe', stationId : 1227},
    2 : {stationName : 'Middle Gorge', stationId : 1226},
    3 : {stationName : 'South Morang', stationId : 1224},
    4 : {stationName : 'Epping', stationId : 1063},
    5 : {stationName : 'Lalor', stationId : 1112},
    6 : {stationName : 'Thomastown', stationId : 1192},
    7 : {stationName : 'Keon Park', stationId : 1109},
    8 : {stationName : 'Ruthven', stationId : 1171},
    9 : {stationName : 'Reservoir', stationId : 1161},
    10 : {stationName : 'Regent', stationId : 1160},
    11 : {stationName : 'Preston', stationId : 1159},
    12 : {stationName : 'Bell', stationId : 1019},
    13 : {stationName : 'Thornbury', stationId : 1193},
    14 : {stationName : 'Croxton', stationId : 1047},
    15 : {stationName : 'Northcote ', stationId : 1147},
    16 : {stationName : 'Merri', stationId : 1125},
    17 : {stationName : 'Rushall', stationId : 1170},
    18 : {stationName : 'Clifton Hill', stationId : 1041},
    19 : {stationName : 'Victoria Park', stationId : 1201},
    20 : {stationName : 'Collingwood', stationId : 1043},
    21 : {stationName : 'North Richmond', stationId : 1145},
    22 : {stationName : 'West Richmond', stationId : 1207},
    23 : {stationName : 'Jolimont', stationId : 1104},
    24 : {stationName : 'Flinders Street', stationId : 1071},
}

var pakenhamLine = {    // 27 stops
    0 : {stationName : 'Pakenham', stationId : 1153},
    1 : {stationName : 'Cardinia Road', stationId : 1223},
    2 : {stationName : 'Officer', stationId : 1151},
    3 : {stationName : 'Beaconsfield', stationId : 1017},
    4 : {stationName : 'Berwick', stationId : 1021},
    5 : {stationName : 'Narre Warren', stationId : 1139},
    6 : {stationName : 'Hallam', stationId : 1085},
    7 : {stationName : 'Dandenong', stationId : 1049},
    8 : {stationName : 'Yarraman', stationId : 1215},
    9 : {stationName : 'Noble Park', stationId : 1142},
    10 : {stationName : 'Sandown Park', stationId : 1172},
    11 : {stationName : 'Springvale', stationId : 1183},
    12 : {stationName : 'Westall', stationId : 1208},
    13 : {stationName : 'Clayton', stationId : 1040},
    14 : {stationName : 'Huntingdale', stationId : 1099},
    15 : {stationName : 'Oakleigh', stationId : 1150},
    16 : {stationName : 'Hughesdale', stationId : 1098},
    17 : {stationName : 'Murrumbeena', stationId : 1138},
    18 : {stationName : 'Carnegie', stationId : 1034},
    19 : {stationName : 'Caulfield', stationId : 1036},
    20 : {stationName : 'Malvern', stationId : 1118},
    21 : {stationName : 'Armadale', stationId : 1008},
    22 : {stationName : 'Toorak', stationId : 1194},
    23 : {stationName : 'Hawksburn', stationId : 1089},
    24 : {stationName : 'South Yarra', stationId : 1180},
    25 : {stationName : 'Richmond', stationId : 1162},
    26 : {stationName : 'Flinders Street', stationId : 1071},
}

var sandringhamLine = { // 14 stops
    0 : {stationName : 'Sandringham', stationId : 1173},
    1 : {stationName : 'Hampton', stationId : 1086},
    2 : {stationName : 'Brighton Beach', stationId : 1027},
    3 : {stationName : 'Middle Brighton', stationId : 1126},
    4 : {stationName : 'North Brighton', stationId : 1143},
    5 : {stationName : 'Gardenvale', stationId : 1074},
    6 : {stationName : 'Elsternwick', stationId : 1061},
    7 : {stationName : 'Ripponlea', stationId : 1165},
    8 : {stationName : 'Balaclava', stationId : 1013},
    9 : {stationName : 'Windsor', stationId : 1214},
    10 : {stationName : 'Prahran', stationId : 1158},
    11 : {stationName : 'South Yarra', stationId : 1180},
    12 : {stationName : 'Richmond', stationId : 1162},
    13 : {stationName : 'Flinders Street', stationId : 1071},
}

var showgroundsRacecourseLine = {   // 5 stops
    0 : {stationName : 'Flemington Racecourse', stationId : 1070},
    1 : {stationName : 'Showgrounds', stationId : 1177},
    2 : {stationName : 'North Melbourne', stationId : 1144},
    3 : {stationName : 'Southern Cross', stationId : 1181},
    4 : {stationName : 'Flinders Street', stationId : 1071},
}

var stonyPointLine = {  // 10 stops
    0 : {stationName : 'Stony Point', stationId : 1185},
    1 : {stationName : 'Crib Point', stationId : 1046},
    2 : {stationName : 'Morradoo', stationId : 1136},
    3 : {stationName : 'Bittern', stationId : 1022},
    4 : {stationName : 'Hastings', stationId : 1088},
    5 : {stationName : 'Tyabb', stationId : 1197},
    6 : {stationName : 'Somerville', stationId : 1178},
    7 : {stationName : 'Baxter', stationId : 1015},
    8 : {stationName : 'Leawarra', stationId : 1114},
    9 : {stationName : 'Frankston', stationId : 1073},
}

var sunburyLine = {     // 16 stops
    0 : {stationName : 'Sunbury', stationId : 1187},
    1 : {stationName : 'Diggers Rest', stationId : 1055},
    2 : {stationName : 'Watergardens', stationId : 1202},
    3 : {stationName : 'Keilor Plains', stationId : 1107},
    4 : {stationName : 'St Albans', stationId : 1184},
    5 : {stationName : 'Ginifer', stationId : 1076},
    6 : {stationName : 'Albion', stationId : 1003},
    7 : {stationName : 'Sunshine', stationId : 1218},
    8 : {stationName : 'Tottenham', stationId : 1196},
    9 : {stationName : 'West Footscray', stationId : 1206},
    10 : {stationName : 'Middle Footscray', stationId : 1127},
    11 : {stationName : 'Footscray', stationId : 1072},
    12 : {stationName : 'South Kensington', stationId : 1179},
    13 : {stationName : 'North Melbourne', stationId : 1144},
    14 : {stationName : 'Southern Cross', stationId : 1181},
    15 : {stationName : 'Flinders Street', stationId : 1071},
}

var upfieldLine = {     // 16 stops
    0 : {stationName : 'Upfield', stationId : 1198},
    1 : {stationName : 'Gowrie', stationId : 1083},
    2 : {stationName : 'Fawkner', stationId : 1066},
    3 : {stationName : 'Merlynston', stationId : 1124},
    4 : {stationName : 'Batman', stationId : 1014},
    5 : {stationName : 'Coburg', stationId : 1042},
    6 : {stationName : 'Moreland', stationId : 1135},
    7 : {stationName : 'Anstey', stationId : 1006},
    8 : {stationName : 'Brunswick', stationId : 1029},
    9 : {stationName : 'Jewell', stationId : 1103},
    10 : {stationName : 'Royal Park', stationId : 1169},
    11 : {stationName : 'Flemington Bridge', stationId : 1069},
    12 : {stationName : 'Macaulay', stationId : 1116},
    13 : {stationName : 'North Melbourne', stationId : 1144},
    14 : {stationName : 'Southern Cross', stationId : 1181},
    15 : {stationName : 'Flinders Street', stationId : 1071},
}

var werribeeLine = {    // 17 stops
    0 : {stationName : 'Werribee', stationId : 1205},
    1 : {stationName : 'Hoppers Crossing', stationId : 1097},
    2 : {stationName : 'Williams Landing', stationId : 1225},
    3 : {stationName : 'Aircraft', stationId : 1220},
    4 : {stationName : 'Laverton', stationId : 1113},
    5 : {stationName : 'Westona', stationId : 1210},
    6 : {stationName : 'Altona', stationId : 1005},
    7 : {stationName : 'Seaholme', stationId : 1175},
    8 : {stationName : 'Newport', stationId : 1141},
    9 : {stationName : 'Spotswood', stationId : 1182},
    10 : {stationName : 'Yarraville', stationId : 1216},
    11 : {stationName : 'Seddon', stationId : 1176},
    12 : {stationName : 'Footscray', stationId : 1072},
    13 : {stationName : 'South Kensington', stationId : 1179},
    14 : {stationName : 'North Melbourne', stationId : 1144},
    15 : {stationName : 'Southern Cross', stationId : 1181},
    16 : {stationName : 'Flinders Street', stationId : 1071},
}

var williamstownLine = {    // 12 stops
    0 : {stationName : 'Williamstown', stationId : 1211},
    1 : {stationName : 'Williamstown Beach', stationId : 1212},
    2 : {stationName : 'North Williamstown', stationId : 1146},
    3 : {stationName : 'Newport', stationId : 1141},
    4 : {stationName : 'Spotswood', stationId : 1182},
    5 : {stationName : 'Yarraville', stationId : 1216},
    6 : {stationName : 'Seddon', stationId : 1176},
    7 : {stationName : 'Footscray', stationId : 1072},
    8 : {stationName : 'South Kensington', stationId : 1179},
    9 : {stationName : 'North Melbourne', stationId : 1144},
    10 : {stationName : 'Southern Cross', stationId : 1181},
    11 : {stationName : 'Flinders Street', stationId : 1071},
}